project:
  type: book
  output-dir: output

book:
  title: "The Shókë language"
  author: "John Kerl"
  # date: "1/16/2023"

  chapters:
    - index.qmd

    - part: "Introduction"
      chapters: 
        - goals.qmd
        - plan.qmd

    - part: "Old Shókë"
      chapters: 
        - old-phonology.qmd
        - old-transcription.qmd
        - old-lexicon.qmd
        - old-syntax.qmd
        - old-examples.qmd
    - part: "Middle Shókë"
    - part: "New Shókë"

# TODO:
# colophon about quarto :D
# bibliography: references.bib

format:
  html:
    theme: cosmo
    mainfont: Baskerville
    fontsize: 1rem
  pdf:
    documentclass: scrreprt
