---
title: Phonology of old Shókë
---

## Sound system

Consonants:

|            | Labial    | Dental      | Post-alveolar | Palatal | Velar    |
-------------|-----------|-------------|---------------|----------|
| Oral Stop  |           |  _t_, _d_   |               | _k_, _g_ |
| Fricative  |           |  _th_, _dh_ | _sh_, _ch_    | _x_      |
| Affricate  |           |             | _ch_, _j_     |          |
| Nasal Stop |  _m_, _n_ |             |               |          |

The _t_ and _d_ are purely dental, as in Spanish.

Vowels:

|            | Front     | Central     | Liquid   | Back    |
-------------|-----------|-------------|----------|---------|
| Close      | _i_       |             |          | _u_     |
| Mid        | _e_       |             | _r_, _l_ | _o_     |
|            | _æ_       |             |          |         |
| Open       | _a_       |             |          |         |

It is to be noted that in Old Shókë, the liquids _r_ and _l_ are not consonants.  They function
exclusively as nuclei in onset-nucleus-coda structures (below).  For example, to pronounce _mrm_,
simply utter the English word _murmur_ but stop after the first syllable.

To do: Few of these sounds are non-English. A bit more could be done in this direction.

## Phonotactics

Syllables are primarily CVC, and secondarily CV.

To do: formulate other restrictions as they arise.

## Transcription

This document uses The Roman alphabet exclusively in place of IPA, with the exception of _æ_.  This
is to avoid the reader misinterpreting _ae_ as a dipthong.

The spelling _ch_ is pronounced as in English _church_; the spelling _x_ is as in Scottish _loch_.

Nothing is silent, including word-final _e_.

## Stress

Stress is always on the penultimate syllable. In the title of this document we write _Shókë_ for
maximum clarity to the first-time reader; for internals of this document we will simply
write _shoke_.
